CREATE DATABASE GUADALTECH;
USE GUADALTECH;
CREATE TABLE EMPLEADOS;
CREATE TABLE EMPLEADOS ( 
    ID INT(11) NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(45) DEFAULT NULL,
     SALARY INT(11) DEFAULT NULL, 
     PRIMARY KEY(ID)
     );
 INSERT INTO EMPLEADOS VALUES(1,'JESÚS MIGUEL',20000),(2,'ANA PEREZ',30000),(3,'BELEN BRAVO',50000);    